In [16]:
from string_embeddings import *

strings = ['AAAAA',
           'AAAAC']
kmer_size = 5
mismatch_embedding = kmer_decomposition_mismatch(strings, kmer_size=kmer_size)
spectral_embedding = kmer_decomposition(strings, kmer_size=kmer_size)
print(spectral_embedding.shape, mismatch_embedding.shape)

(2, 1024) (2, 1280)


In [17]:
from kernel_functions import linear_kernel, mismatch_kernel

linear_kernel(spectral_embedding, spectral_embedding)

array([[1., 0.],
       [0., 1.]])

In [18]:
mismatch_final_embedding = (mismatch_embedding, spectral_embedding)
mismatch_kernel(mismatch_final_embedding, mismatch_final_embedding)

array([[1., 1.],
       [1., 1.]])

In [21]:
strings = ['AAAAA',
           'TTTTT',]
kmer_size = 5
spectral_embedding_reverse = kmer_decomposition(strings, kmer_size=kmer_size, reverse=True)
spectral_embedding_reverse

<2x512 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [22]:
linear_kernel(spectral_embedding_reverse, spectral_embedding_reverse)

array([[1., 1.],
       [1., 1.]])

### Weighted Degree Kernel (WIP)

In [ ]:
kmer_decomposition_positional(strings, kmer_size=5)

In [3]:
def weighted_degree_kernel(X):
    pass